### ISSUE TITLE
WiFi stopped working from nowhere

### ISSUE THREAD

**Issue by JPZV** [UnexpectedMaker/esp32s3#11]
Hi! I love this board, and I'm making a smart Xylobands with a fork of [WLED](https://github.com/Aircoookie/WLED/). I don't like the TinyS3 to be very hot while using WiFi so I turn it off after a minute because it's not needed for my project, except for the initial setup.

But right now I have a problem because the WiFi doesn't works at all, and the board overheats a lot, specially with the USB connected (using the Battery will make the board overheat but not that much). At the morning it was working correctly, but from nowhere it stopped to do.

WLED uses the AP Mode, and it doesn't shows up neither on my computer nor on my phone. I also tested a example project from Arduino-esp32 which connects to my network and it also fails (it tries to connect to my network infinitely while another ESP32 would connect almost intermediately)

What can I do? There is no error message apparently so I don't have any clue

~~PS: Viewing the datasheet, there is a capacitor named C5, but on my board that seems to be a resistor, which also is in short (i.e. It has continuity between its terminals). Is it normal? Or is it fried somehow?~~ After viewing the datasheet for others type of ESP32, it seems to be normal to have a zero ohms resistor between the antenna and the ESP32

**Comment by UnexpectedMaker** [comment]
Can you join my discord server and post for help in there in the `#um-hardware` help section? That's the best place to get support from me and others in the community. 
https://discord.gg/xAHpApP

Thanks :)
