### ISSUE TITLE
External Anntena ProS3

### ISSUE THREAD

**Issue by osorioen** [UnexpectedMaker/esp32s3#13]
Hi. I need to connect a external antenna to ProS3 . How can I do it?

**Comment by UnexpectedMaker** [comment]
It's not really possible. Even taking off the SMD antenna won't allow you to attach an external antenna.

**Comment by UnexpectedMaker** [comment]
Just wanted to let you know I've released new S3 boards with u.FL connectors....
https://unexpectedmaker.com/shop/pros3-ufl
