### ISSUE TITLE
Error in schematic ?

### ISSUE THREAD

**Issue by eleroy** [UnexpectedMaker/esp32s3#16]
Hi,

Thank you for your boards, I love them.

I wonder if there is an error in the schematic [here](https://github.com/UnexpectedMaker/esp32s3/blob/main/schematics/schematic-tinys3.pdf).

I'm not the best at electronics but isn't The P-mos T3 used for switching off the battery when connecting the USB upside down ? 

Usually for a P-mos, the current is meant to flow from source to drain.

Best,

Edouard.

**Comment by UnexpectedMaker** [comment]
The schematic for the power section may look unconventional, but it is correct :)

**Comment by eleroy** [comment]
Ah yes, I got it, thanks.
