### ISSUE TITLE
Using the voltage reader function for higher voltages?

### ISSUE THREAD

**Issue by anglerfish27** [UnexpectedMaker/esp32s3#17]
Is it possible to use the code for checking the amount of voltage of the battery to a much higher voltage if you make the appropriate changes in the helper file? Say I wanted to see what the voltage of a 48V battery is, would that work? Would other parts of the code need modification besides the part that sets it to 4.2v currently?

Cheers.

**Comment by UnexpectedMaker** [comment]
Absolutely not! You’ll blow up the IO on the ESP32 chip. The voltage divider on the board is there to reduce the voltage going to the IO to make a 4.2V max voltage fit into the ADC range.
