### ISSUE TITLE
FeatherS3 Pin clarification required from datasheet

### ISSUE THREAD

**Issue by sukesh-ak** [UnexpectedMaker/esp32s3#4]
Are the 2 Stemma QT connectors using the same PINS?

I am trying to use one of them for UART and one for I2C.
Also the labels for Vertical connector is mixed up.

![image](https://user-images.githubusercontent.com/53081362/165083105-da4e33cc-4b4b-4dba-a4a6-5cb93fcdf5f4.png)

**Comment by UnexpectedMaker** [comment]
Stemma is only I2C. Yes they share the same I2C pins.

**Comment by UnexpectedMaker** [comment]
These are questions for my discord server. Please join there.
