### ISSUE TITLE
D5?

### ISSUE THREAD

**Issue by gwolber** [UnexpectedMaker/esp32s3#7]
Hi, I really love the s3tiny, congratulations on this great work! 
However, I encountered a problem: After connecting 5V to the USB power pin on the breakout header, my board cannot be powered over the USB port anymore; D5 seems dead for whatever reason. Could you tell me which type of Z-Diode D5 exactly is? Or is there even a parts list that I did not find?
Thanks, Gerhard

**Comment by UnexpectedMaker** [comment]
Oh no! Are you sure you didn't short the pins somehow? You should be able to have the USB connected and the 5V rail connected to external power at the same time.  That's what the back feed diode is there for.
Anyhow, it's a 1A SOD523 Schottky diode, not a Zenner. Any 1A  Schottky will do if you plan on replacing it.

**Comment by gwolber** [comment]
Great, thanks!! :)
