### ISSUE TITLE
Backward pins in KiCAD schematic lib for FeatherS3 and TinyS3

### ISSUE THREAD

**Issue by username115** [UnexpectedMaker/esp32s3#8]
All of the pins in the KiCAD schematic library for the FeatherS3 an TinyS3 are backwards. In KiCAD, the little circle is used as the attachment point, and it should be facing outward. Also, the pin labels should be internal to the part.

The ProS3 has its pins in the correct orientation

**Comment by UnexpectedMaker** [comment]
That's been fixed, thanks very much for spotting this!
